### ISSUE TITLE
Countable -> DefinitelyFinite

### ISSUE THREAD

**Issue by glyn** [shaardie/set#2]
Since the infinite set of natural numbers is countable, better to choose a different method name, such as `DefinitelyFinite`.

**Comment by shaardie** [comment]
This is a good point.  Unfortunately this is part of the interface, so I have to look how to fix this best.

**Comment by shaardie** [comment]
Added `DefinitelyFinite()` to the Set interface. `Countable()` is marked as deprecated and will be removed later.
